# Generated by Django 5.2.12 on 2026-04-12 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('home_type', models.CharField(choices=[('House', 'House'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('Land', 'Land')], max_length=50)),
                ('city', models.CharField(choices=[('Omaha', 'Omaha'), ('Lincoln', 'Lincoln'), ('Bellevue', 'Bellevue'), ('Council Bluffs', 'Council Bluffs')], max_length=100)),
                ('state', models.CharField(choices=[('NE', 'Nebraska'), ('IA', 'Iowa')], max_length=2)),
                ('neighborhood', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Sold', 'Sold')], default='Active', max_length=20)),
                ('visibility', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('garage', models.PositiveIntegerField()),
                ('year_built', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_photos/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.property')),
            ],
        ),
    ]
