# Generated by Django 5.2.12 on 2026-04-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmahaResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('events', 'Area Event'), ('places', 'Places to Visit'), ('family', 'Family Activities'), ('food', 'Places to Eat')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
