# Generated by Django 5.2.12 on 2026-04-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_omaharesource'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Carlos Kosala', max_length=100)),
                ('office_address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('biography', models.TextField(blank=True)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='agent_portraits/')),
            ],
        ),
    ]
